builtin.go, builtin_test.go, cmd/1pl/main.go, engine.go, engine_test.go, interpreter.go, interpreter_test.go, parser.go, parser_test.go, solutions.go
Also bindvars to imitate sql/sqlx like interface to make it more intuitive.
=> Introduce Solutions which is analogous to sql.Rows

engine/number.go, engine/number_test.go
=> add evaluable functor: min

engine/number.go, engine/number_test.go
=> add evaluable functor: integer power

engine/number.go, engine/number_test.go
=> add evaluable functor: asin

engine/number.go, engine/number_test.go
=> add evaluable functor: acos

engine/number.go, engine/number_test.go
=> add evaluable functor: atan2

engine/number.go, engine/number_test.go
=> add evaluable functor: tan

engine/number.go, engine/number_test.go
=> add evaluable functor: pi

engine/number.go, engine/number_test.go
=> add evaluable functor: xor

engine/parser.go, engine/parser_test.go
=> make the default value for double_quotes to chars.

README.md, cmd/1pl/main.go, interpreter.go, interpreter_test.go
This project is merely a Go library so a top level is out of the scope.
Yet, it's nice to have one for testing purposes and actually I've been using `1pl` for that purpose.
This PR fixes some rough edges of `1pl` so that others can try it and test the default language `prolog.New()` provides.
=> a bit more presentable top level

interpreter_test.go, solutions_test.go
add some examples including ones that relate to placeholders.
`ExampleSolutions_Scan_list()` is the answer to https://github.com/ichiban/prolog/issues/160#issuecomment-1068185293
=> add placeholder examples

README.md, engine/atom.go, engine/builtin.go, engine/builtin_test.go, engine/compound.go, engine/term.go, engine/variable.go, engine/variable_test.go
=> add `variable_names` write-option

engine/lexer.go, engine/lexer_test.go, engine/parser.go
=> accept a period as an atom

.github/workflows/go.yml, cmd/1pl/interpreter.go, cmd/1pl/interpreter_test.go, cmd/1pl/main.go, codecov.yml, engine/builtin.go, engine/builtin_test.go
=> add call_nth/2

engine/builtin.go, engine/builtin_test.go, interpreter_test.go
=> fix boundary checking error for arg/2 (Thanks to @rosbit)

engine/builtin.go, engine/builtin_test.go
=> fix exceptions for write-option variable_names/2

engine/builtin.go, engine/builtin_test.go, engine/exception.go, engine/iterator.go
=> type check output list arguments

engine/builtin.go, engine/builtin_test.go, interpreter_test.go
https://github.com/ichiban/prolog/issues/188#issuecomment-1186180393
=> The character sequence for a variable begins with `_` (7.10.5.a).

engine/lexer.go, engine/lexer_test.go
=> generalize small letter char

cmd/1pl/main.go, engine/parser.go, engine/parser_test.go
https://github.com/ichiban/prolog/issues/190#issuecomment-1189904293
=> Cook user input

cmd/1pl/main.go
https://github.com/ichiban/prolog/issues/190#issuecomment-1189904293
=> fix handling of newlines in 1pl

engine/builtin.go, engine/builtin_test.go
=> fix Term =.. List for the case that Term is atomic and List is a partial list.

interpreter.go, interpreter_test.go
=> fix consult/1 error

.github/workflows/go.yml, engine/atom.go, engine/builtin.go, engine/builtin_test.go, engine/exception.go, engine/malloc.go, go.mod
=> respect debug.SetMemoryLimit() when allocate a slice.

examples/call_go_from_prolog/main.go, examples/dcg/main.go
=> update examples to respect double_quotes flag

engine/atom.go, engine/builtin.go, engine/builtin_test.go, engine/compound.go, engine/term.go
https://github.com/ichiban/prolog/issues/297
=> fix truncation of already visited compounds in writeCommpoundVisit().

engine/builtin_test.go, engine/compound.go
https://github.com/ichiban/prolog/issues/297#issuecomment-1646750461
=> prioritize max_depth over cycle detection

engine/builtin.go, engine/builtin_test.go
https://github.com/ichiban/prolog/issues/309
=> a predicate created by {asserta, assertz}/1 must be public.

engine/variable.go, engine/variable_test.go, interpreter_test.go
https://github.com/ichiban/prolog/issues/318
=> fix variable's WriteTerm() when following/followed by a letter-digit operator

engine/lexer.go, engine/lexer_test.go
https://github.com/ichiban/prolog/issues/326
=> fix mishandling of **/ at the end of bracketed comment.

engine/text.go
https://github.com/ichiban/prolog/issues/329
=> avoid recursive file load.

engine/atom.go
=> Fix typo in `atomPastEndOfStream` definition
