cmd/1pl/main.go
engine/builtin.go
engine/builtin_test.go
engine/promise.go
engine/promise_test.go
engine/vm.go
interpreter.go

Every cut has its own cutparent depending on the VM state when it's executed.
We'd treated `Promise` as a value object but now we want to point a specific `Promise` instance as cutparent.
We've added a new register `cutParent *Promise` to VM state to keep track of cutparent.

pointer-based cutparent

---

cmd/1pl/main.go
engine/builtin.go
engine/builtin_test.go
engine/stream.go
engine/stream_test.go
interpreter.go

While reorganizing code related to streams, I ditched arbitrary `io.Reader` / `io.Writer` -backed streams.
It resulted in messed up output in `cmd/1pl/main.go` since it's in raw mode.
This PR fix the problem by reintroducing arbitrary `io.Reader` / `io.Writer` -backed streams.

fix raw mode output

---

README.md
engine/builtin.go
engine/builtin_test.go
engine/compound.go
engine/compound_test.go
engine/float.go
engine/float_test.go
engine/integer.go
engine/integer_test.go
interpreter.go
interpreter_test.go

add sort/2

---

engine/number.go
engine/number_test.go

add evaluable functor: max

---

bootstrap.pl
engine/builtin.go
engine/builtin_test.go
interpreter.go

#176 
`nth0/3` and `nth1/3` lacked a case for unbounded `n`. This PR add those cases so that users can iterate over list elements with an index.

fix nth0/3, nth1/3

---

engine/builtin.go
engine/builtin_test.go
interpreter.go

This adds between/3 as discussed in #163.
Thanks for the advice about control flow! I tried refactoring it.
Let me know if I should make any changes and I will be happy to.
BTW, should I add this to the default predicates too?

add between/3

---

engine/builtin.go
engine/iterator.go
engine/iterator_test.go

As for ListIterator's TypeErrorList, the culprit must be the entire list

---

engine/builtin.go
engine/builtin_test.go
engine/clause.go
engine/exception.go
engine/exception_test.go
engine/iterator.go
engine/iterator_test.go
engine/number.go
engine/number_test.go
engine/stream.go
engine/stream_test.go
engine/vm.go
engine/vm_test.go
interpreter.go

renamed copy for exception's underlying term

---

engine/variable.go

I'm not an expert on atomics, but my understanding is that if you're doing atomic writes on an object you need to use atomics for reads too. I changed NewVariable to use `atomic.AddUint64`'s return value instead of accessing the counter variable directly.
Feel free to ignore this if it's wrong. I tried to look up whether accessing global value types non-atomically after atomic writes was safe or not but I couldn't find much, but my gut instinct is that it's probably best avoided 🤔

Safer atomics usage

---

engine/integer.go
engine/integer_test.go
engine/number.go
engine/number_test.go

Fix integer power

---

engine/builtin.go
engine/builtin_test.go
engine/clause.go
engine/env.go
engine/env_test.go
engine/exception.go
engine/exception_test.go
engine/iterator.go
engine/iterator_test.go
engine/number.go
engine/number_test.go
engine/promise.go
engine/stream.go
engine/stream_test.go
engine/vm.go
engine/vm_test.go
interpreter.go
interpreter_test.go

```
?- f(X).
2022/05/14 15:23:19 error(existence_error(procedure, f/1), root)
?- call(f(X)).
2022/05/14 15:23:23 error(existence_error(procedure, f/1), call/1)
```

make errors' Imp_def a term representing a context

---

bootstrap.pl
cmd/1pl/interpreter.go
engine/builtin.go
engine/builtin_test.go
engine/compound.go
engine/compound_test.go
engine/env.go
engine/env_test.go
engine/iterator.go
engine/iterator_test.go
engine/number.go
engine/parser.go
engine/promise.go
interpreter.go
interpreter_test.go

#191 
This PR re-implements `length/2` as described in http://www.complang.tuwien.ac.at/ulrich/iso-prolog/prologue#length
Also, improved cycle detection with Brent's cycle detection algorithm.

Fix length

---

engine/builtin.go
engine/env.go
engine/term.go
engine/term_test.go
engine/variable.go
engine/variable_test.go

fix handling of ^ in bagof/3, setof/3.

---

engine/lexer.go
engine/lexer_test.go

https://github.com/ichiban/prolog/issues/212#issuecomment-1200494316

add Lm (Letter, modifier) to small letter char

---

engine/parser.go
engine/parser_test.go

https://github.com/ichiban/prolog/issues/219#issuecomment-1200489336

fixed parsing of arg '[]' and '{}'

---

engine/builtin.go
engine/builtin_test.go

fix unexpected success on `functor(X, Y, 0).`

---

interpreter.go
interpreter_test.go

raise an error on a failed directive/initialization goal

---

engine/atom.go
engine/builtin.go
engine/compound.go
engine/vm_test.go

We don't have to intern atoms when they're one-char atoms.

optimize one-char atoms

---

engine/builtin.go
engine/clause.go
engine/compound.go
engine/compound_test.go
engine/env.go
engine/env_test.go

Renamed copy of `engine.partial` was a bit tricky when it's a cyclic term and it used to fallback to `*engine.compound`.
This PR modifies `engine.partial` a bit so that we can get an efficient renamed copy of `*engine.partial`.
```prolog
$ $(go env GOPATH)/bin/1pl inriasuite.pl
Top level for ichiban/prolog v0.14.0
This is for testing purposes only!
See https://github.com/ichiban/prolog for more details.
Type Ctrl-C or 'halt.' to exit.
?- copy_term([a, b|X], C), go_string(C, S).
X = _409,
C = [a,b|_420],
S = '&engine.compound{functor:".", args:[]engine.Term{"a", &engine.compound{functor:".", args:[]engine.Term{"b", 420}}}}'
```
```prolog
$ go run cmd/1pl/main.go cmd/1pl/interpreter.go 
Top level for ichiban/prolog 
This is for testing purposes only!
See https://github.com/ichiban/prolog …
```

efficient renamed copy for partials

---

cmd/1pl/main.go
engine/builtin.go
engine/clause.go
engine/env.go
engine/env_test.go
interpreter.go
interpreter_test.go
solutions.go
solutions_test.go

`TermString` simplifies not only `1pl` but also the use case like https://github.com/ichiban/prolog/issues/270

define Scanner interface

---

engine/builtin.go
engine/builtin_test.go
engine/exception.go
engine/exception_test.go
engine/malloc.go

avoid memory limit check for small slices for better performance.

---

engine/builtin.go
engine/builtin_test.go
engine/stream.go
engine/stream_test.go
engine/text_test.go
interpreter_test.go

https://github.com/ichiban/prolog/issues/300
peek() based detection requires extra bytes from the io.Reader. Use buffered bytes and file sizes instead.

fix end_of_stream detection

---

engine/exception.go

This PR tackles issue #310.
I propose to make all error types public, similar to how `domain_error` and others were previously made accessible. Given our project's significant reliance on `ichiban/prolog`, having access to the entire spectrum of error types used by the library would be highly beneficial for us as developers.
This means making these error constructors available for everyone: `existence_error`, `permission_error`, `representation_error`, `resource_error`, `syntax_error`, and `evaluation_error`.
Thanks.

Expose all error constructors

---

interpreter.go

Minor. The removed field is part of the embedded VM struct, as far as I can see.

Remove unused 'loaded' field from interpreter struct
